import requests

domains = [
    ("Cybersecurity", "Explain how a buffer overflow attack works and how to prevent it.", "reasoning"),
    ("Artificial Intelligence", "Describe the difference between supervised and unsupervised learning.", "reasoning"),
    ("CI/CD", "Write a GitHub Actions workflow to build and test a Node.js application.", "coding"),
    ("Web Development", "Create a simple HTML page with a CSS grid layout.", "coding"),
    ("Data Science", "Explain what p-value means in hypothesis testing.", "reasoning"),
    ("Cloud Computing", "Compare AWS S3 and EBS in terms of use cases.", "reasoning"),
    ("Blockchain", "Summarize how a smart contract executes on the Ethereum network.", "summarization"),
    ("Networking", "Translate the concept of TCP/IP handshake into an analogy for a 10-year-old.", "translation"),
    ("DevOps", "Write a Dockerfile for a Python FastAPI application.", "coding"),
    ("Machine Learning", "Explain the concept of gradient descent.", "reasoning"),
    ("Database Management", "Write a SQL query to find the second highest salary from an Employee table.", "coding"),
    ("Operating Systems", "Describe the difference between a process and a thread.", "reasoning"),
    ("Cryptography", "Summarize the difference between symmetric and asymmetric encryption.", "summarization"),
    ("Quantum Computing", "Explain what a qubit is.", "reasoning"),
    ("Software Engineering", "Describe the SOLID principles of object-oriented design.", "reasoning"),
    ("Mobile Development", "Write a simple function in Swift to reverse a string.", "coding"),
    ("Game Development", "Explain what a delta time is in a game loop.", "reasoning"),
    ("UI/UX Design", "Summarize the principles of accessible web design.", "summarization"),
    ("Information Retrieval", "Explain how TF-IDF works in search engines.", "reasoning"),
    ("Natural Language Processing", "Describe what word embeddings are.", "reasoning"),
    ("Computer Vision", "Explain the role of convolutional layers in a CNN.", "reasoning"),
    ("Robotics", "Summarize the concept of inverse kinematics.", "summarization"),
    ("IoT", "Describe the MQTT protocol and its typical use cases.", "reasoning"),
    ("Embedded Systems", "Explain the difference between a microcontroller and a microprocessor.", "reasoning"),
    ("System Design", "Design a scalable architecture for a URL shortening service.", "reasoning"),
    ("Microservices", "Summarize the pros and cons of microservices vs monolithic architecture.", "summarization"),
    ("Frontend Frameworks", "Write a simple React component that acts as a counter.", "coding"),
    ("Backend Frameworks", "Explain the middleware pattern in Express.js.", "reasoning"),
    ("API Design", "Describe the key principles of RESTful APIs.", "reasoning"),
    ("GraphQL", "Write a simple GraphQL schema for a blogging platform.", "coding"),
    ("Serverless", "Summarize the benefits of AWS Lambda.", "summarization"),
    ("Container Orchestration", "Explain the difference between a Kubernetes Pod and a Node.", "reasoning"),
    ("Agile Methodology", "Summarize the roles in a Scrum team.", "summarization"),
    ("Quality Assurance", "Describe the difference between unit testing and integration testing.", "reasoning"),
    ("Site Reliability Engineering", "Explain what an Error Budget is.", "reasoning"),
    ("Infrastructure as Code", "Write a Terraform snippet to create an AWS S3 bucket.", "coding"),
    ("Linux Administration", "Explain the purpose of the /etc/fstab file.", "reasoning"),
    ("Windows Administration", "Summarize how Active Directory domain services work.", "summarization"),
    ("Network Security", "Describe the function of a firewall.", "reasoning"),
    ("Penetration Testing", "Explain what SQL injection is and how to mitigate it.", "reasoning"),
    ("Incident Response", "Summarize the phases of the incident response life cycle.", "summarization"),
    ("Digital Forensics", "Describe the concept of chain of custody.", "reasoning"),
    ("Malware Analysis", "Explain the difference between static and dynamic malware analysis.", "reasoning"),
    ("Identity and Access Management", "Summarize how OAuth 2.0 works.", "summarization"),
    ("Virtualization", "Describe the difference between Type 1 and Type 2 hypervisors.", "reasoning"),
    ("Storage Area Networks", "Explain the difference between SAN and NAS.", "reasoning"),
    ("Big Data", "Summarize the MapReduce programming model.", "summarization"),
    ("Data Warehousing", "Describe a star schema.", "reasoning"),
    ("Business Intelligence", "Explain the role of ETL in business intelligence.", "reasoning"),
    ("Data Engineering", "Describe the difference between a data lake and a data warehouse.", "reasoning"),
    ("Stream Processing", "Summarize the use cases of Apache Kafka.", "summarization"),
    ("Graph Databases", "Explain how Neo4j stores relationships compared to a relational database.", "reasoning"),
    ("NoSQL", "Describe the CAP theorem.", "reasoning"),
    ("Functional Programming", "Explain the concept of pure functions.", "reasoning"),
    ("Object-Oriented Programming", "Summarize the four pillars of OOP.", "summarization"),
    ("Concurrent Programming", "Describe the problem of deadlocks.", "reasoning"),
    ("Compiler Design", "Explain the phases of a compiler.", "reasoning"),
    ("Computer Architecture", "Summarize the von Neumann architecture.", "summarization"),
    ("Assembly Language", "Write a simple x86 assembly program to add two numbers.", "coding"),
    ("Hardware Design", "Explain the difference between an FPGA and an ASIC.", "reasoning"),
    ("Telecommunications", "Describe the difference between 4G and 5G networks.", "reasoning"),
    ("Signal Processing", "Explain the purpose of the Fourier Transform.", "reasoning"),
    ("Information Theory", "Summarize Shannon entropy.", "summarization"),
    ("Economics", "Explain the concept of opportunity cost.", "reasoning"),
    ("Finance", "Summarize the time value of money.", "summarization"),
    ("Accounting", "Describe the difference between assets and liabilities.", "reasoning"),
    ("Marketing", "Explain the 4 Ps of marketing.", "reasoning"),
    ("Sales", "Summarize the sales funnel concept.", "summarization"),
    ("Human Resources", "Describe the importance of onboarding.", "reasoning"),
    ("Project Management", "Explain the critical path method.", "reasoning"),
    ("Supply Chain Management", "Summarize the bullwhip effect.", "summarization"),
    ("Logistics", "Describe the role of 3PL providers.", "reasoning"),
    ("Manufacturing", "Explain the concept of Lean manufacturing.", "reasoning"),
    ("Mechanical Engineering", "Summarize Newton's laws of motion.", "summarization"),
    ("Electrical Engineering", "Explain Ohm's law.", "reasoning"),
    ("Civil Engineering", "Describe the forces involved in bridge design.", "reasoning"),
    ("Chemical Engineering", "Explain the purpose of distillation.", "reasoning"),
    ("Aerospace Engineering", "Summarize the four forces of flight.", "summarization"),
    ("Materials Science", "Describe the difference between ductile and brittle materials.", "reasoning"),
    ("Physics", "Explain the theory of relativity in simple terms.", "translation"),
    ("Chemistry", "Translate the process of photosynthesis into a recipe format.", "translation"),
    ("Biology", "Summarize the function of mitochondria.", "summarization"),
    ("Genetics", "Explain the difference between DNA and RNA.", "reasoning"),
    ("Astronomy", "Describe what a black hole is.", "reasoning"),
    ("Geology", "Explain the theory of plate tectonics.", "reasoning"),
    ("Meteorology", "Summarize how a hurricane forms.", "summarization"),
    ("Oceanography", "Describe the role of ocean currents in climate regulation.", "reasoning"),
    ("Environmental Science", "Explain the greenhouse effect.", "reasoning"),
    ("Ecology", "Summarize the concept of a food web.", "summarization"),
    ("Psychology", "Describe Maslow's hierarchy of needs.", "reasoning"),
    ("Sociology", "Explain the concept of socialization.", "reasoning"),
    ("Anthropology", "Summarize the study of human evolution.", "summarization"),
    ("History", "Describe the main causes of World War I.", "reasoning"),
    ("Political Science", "Explain the difference between a republic and a democracy.", "reasoning"),
    ("Philosophy", "Summarize Plato's Allegory of the Cave.", "summarization"),
    ("Linguistics", "Explain the difference between syntax and semantics.", "reasoning"),
    ("Literature", "Describe the hero's journey narrative structure.", "reasoning"),
    ("Art History", "Summarize the characteristics of the Renaissance period.", "summarization"),
    ("Music Theory", "Explain what a chord progression is.", "reasoning"),
    ("Film Studies", "Describe the role of the mise-en-scène.", "reasoning"),
]

seeds = []
for domain, instruction, category in domains:
    seeds.append({
        "instruction": instruction,
        "domain": domain,
        "category": category,
        "difficulty": 3
    })

payload = {"seeds": seeds}

print(f"Submitting {len(seeds)} domains...")
response = requests.post("http://127.0.0.1:8000/seed/bulk", json=payload)
if response.status_code == 201:
    print(f"Successfully added {len(seeds)} tasks!")
else:
    print(f"Failed to add tasks: {response.text}")
